source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'pry-byebug'
gem 'rake'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
gem 'minitest'
