source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'pry-byebug'
gem 'rake', '~> 12.3'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
gem 'minitest'
gem 'activesupport', '~> 5.1', '>= 5.1.5'
gem 'railties'
gem 'bcrypt'
